### ISSUE TITLE
Can Loot Summoned Creatures

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#10]
I know this was an issue in the older versions for Classic, and I just tested to make sure it still exists in this version.

When you make a summoned creature (eg. Flame Atronach, Frost Atronach, Storm Atronach, etc.), QuickLoot allows you to loot them during their death animation (the moment before they disappear). If you 'already' had them targeted as they're dying, the menu does not pop up, but if you move the cursor to them 'while' they're dying, then the menu appears.

I noticed how you resolved the issue with ghosts. The same should be possible here - all summoned actor records should have the "Summonable" flag on them.

**Comment by SniffleMan** [comment]
Fixed in 1.6.3

**Comment by Velgus** [comment]
I tested and the issue is indeed fixed. Thank you, closing the issue.
