### ISSUE TITLE
CTD while "hovering" over lootable object

### ISSUE THREAD

**Issue by SilentPrayeCG** [SniffleMan/QuickLootRE#11]
Tried version that i downloaded one or two days ago, works.
Saw update 1.6.4, installed it, and it's just cdt when i look at lootable oject.
But i have bunch of stuff installed, if it need to check something in raw Skyrim then a bit later, tomorrow maybe.
Just decide report this, regardless of my Skyrim's state.

**Comment by King-Troller** [comment]
I had this issue yesterday after updating.
1. Uninstall quickloot
2. Start the game. Wait a few hours, save, and quit.
3. Reinstall quickloot
Thats all I did and it stopped crashing for me. Idk what part if any of that fixed it or if it was a coincidence, but it's worth a shot.

**Comment by SilentPrayeCG** [comment]
Stupid question, but i hope you mean ingame hours?)))

**Comment by King-Troller** [comment]
Its probably specific to your setup then. I haven't been having any issues and I'm using a ton of mods. You could try the most recent release and see if it fixes it.

**Comment by Velgus** [comment]
1.6.5 is the latest.

I didn't end up using 1.6.4 (1.6.5 was out by the time I noticed), but 1.6.5 does not seem to have this crashing issue.

**Comment by Velgus** [comment]
You likely have your URL for the GitHub release filtered by "tag". Look at your URL and you will likely see "[...]/tag/1.6.4" at the end. Use the either:

- https://github.com/SniffleMan/QuickLootRE/releases/latest (latest release URL)
- https://github.com/SniffleMan/QuickLootRE/releases (all releases URL)

**Comment by SilentPrayeCG** [comment]
At first i watch here https://github.com/SniffleMan/QuickLootRE because sometimes all stuff needed is here
But then i checked https://github.com/SniffleMan/QuickLootRE/releases and find it), it just when i start this "issue", 1.6.5 wasn't released yet.
