### ISSUE TITLE
Quickly Opening "Full" Inventory Does Not Close QuickLoot (and "Take All" bug)

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#13]
**Issue 1:** 
If you press R to open the full inventory menu _immediately_ after targeting a container, then the QuickLoot menu stays open while in the full inventory menu. While in the menu this way, you cannot close the full inventory menu via "Tab" - only "Esc" or "R" (Take All). 

You are able to scroll through the QuickMenu list with the mouse wheel, and loot with E, despite the full inventory being open.

This will not occur if the container has an animation (eg. a lid opening) - I tested it with NPC corpses. This will also not occur if you just hold "R" while moving the cursor over a container.

**Reproduction:**
1. Find a container that _does not_ have animations of any sort when opening the 'full' inventory.
2. Move the target reticle to the container and _immediately_ press "R" (you may not get it the first attempt, repeat until it happens).

**Image:** https://i.imgur.com/qtoZc9E.png

**Issue 2 (Take All Bug):**
If a ~an _empty_~ container with _no opening animation_ is opened to the full inventory menu ("R" from QuickLoot), pressing "R" again ("Take All" from full inventory menu) closes _then immediately re-opens_ the full inventory menu. The full inventory menu should not be re-opened when doing this.

**Reproduction:**
1. Find a ~an _empty_~ container that _does not_ have animations of any sort when opening the 'full' inventory.
2. Open the full inventory by targeting the container and pressing "R".
3. Press "R" again to activate the "Take All" function from the full inventory.

EDIT: The container _does not_ actually need to be empty upon double-checking, but still must have no opening animation.

**Comment by SniffleMan** [comment]
Both should be fixed in 1.7.3

**Comment by Velgus** [comment]
I just tested 1.7.3 quickly - I can no longer reproduce Issue 1 (the QuickLoot menu always closes). However, Issue 2 still seems to be active - the full inventory still re-appears after using "Take All" from within it.

**Comment by SniffleMan** [comment]
Issue #2 should now be fixed in 1.7.4
Thanks for the on key up tip

**Comment by Velgus** [comment]
I'll test this and the other issue tomorrow. If it's resolved, I'll close the issues. Thank you very much for your work on this mod and responding so quickly to bug reports/input!

**Comment by Velgus** [comment]
Unfortunately Issue 2 still seems to be present for dead NPCs and objects without animations (eg. I tried it on a non-animated sack), alongside some additional issues I found with the fix for the pickpocket issue (#14).

**Comment by SniffleMan** [comment]
Should be fixed for real this time on 1.7.5

**Comment by Velgus** [comment]
Issue 2 is fixed now. I'm still having some slight issues with the pickpocketing thing, but that's more related to #14, so I'm closing this now. I'll post my updates on that issue. Thank you!
