### ISSUE TITLE
Additional Sorting Request - Value/Weight

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#16]
Just a request for a sorting option that functions as Value/Weight. 

This would probably be the 'most' useful sorting option for most people, as it prioritizes things that players will 'usually' want to loot (eg. gold, lockpicks, jewelry, soul gems, enchanted items, etc.). 

Anything with 0 weight (such as gold) shouldn't perform the check, and instead just be placed directly at the top.

**Comment by King-Troller** [comment]
This is unrelated to this mod, but have you looked into using AutoHarvest to pickup all those smaller types of items? I started using it just for gold, jewels, soul gems, and jewelry and combined with Quick Loot saves me so much time while looting. Only downside is it can take some configuring to make it only pickup what you want.

**Comment by SniffleMan** [comment]
Added in 1.7.0
