### ISSUE TITLE
Opacity bug (for real)

### ISSUE THREAD

**Issue by thebowchild** [SniffleMan/QuickLootRE#19]
I believe it is in fact a bug, on older versions I only changed the opacity line to 75 and it got a bit of transparency, but it still was an outlined box (I could change it to any value and it changed opacity accordingly). Now it doesnt matter what value I put, the outlined box its gone 100%. Here a image, I hope this helps explain it, this is on the lastest version (1.7.1) https://imgur.com/Lsy4Ckw. And this is on the version 1.5.0 https://imgur.com/uj3erLF. Sorry for spaming you with this, but I think its something to take a look at. (If I am wrong again, I apologize for spamming).

**Comment by SniffleMan** [comment]
I changed the way the interface for settings accepted their properties. You have to maintain the floating point property of the entry, or it won't accept the input correctly. I do not consider this a bug.

**Comment by SniffleMan** [comment]
50.0 instead of 50

**Comment by thebowchild** [comment]
Well, that was simple haha, TY a lot for the patience! You are doing an amazing job with this mod

**Comment by SniffleMan** [comment]
Fixed in 1.7.2
