### ISSUE TITLE
Equipped items not showing up 

### ISSUE THREAD

**Issue by thebowchild** [SniffleMan/QuickLootRE#20]
On the latest version all equipped items and gold doesnt show up on the quick loot menu, but they appear on the vanilla menu once I click search. From what I understood equipped items are invisible on the quick loot menu, because when looting the rest of the unnequipped items, if I keep clicking it eventually the hidden items go to my inventory (its not on pickpocketing with the perks, its on normal looting dead npcs)

**Comment by SniffleMan** [comment]
Should be fixed in 1.7.5

**Comment by thebowchild** [comment]
Version 1.7.5 doesnt work for me, I get no errors nor CTD, but the menu is simply not there (its like I dont have the mod activated, but I do)

**Comment by Velgus** [comment]
Something else is wrong on your end @thebowchild. I just finished testing the mod for #14 being fixed or not, and the menu appearing.

Are you sure you're not in combat (default config disables QuickLoot in combat). Otherwise, just try re-installing and making sure all the files are there properly.

**Comment by thebowchild** [comment]
Ok forget what I just said, I figured it out the problem. If I enable the "disable if empty" then the looting menu is gone

**Comment by SniffleMan** [comment]
Should be fixed in 1.7.10
