### ISSUE TITLE
More compatibility for hunterborn (suggestion)

### ISSUE THREAD

**Issue by thebowchild** [SniffleMan/QuickLootRE#24]
Hey, I was thinking about what could be done so this mod gets more compatible with hunterborn. Could you maybe add a configuration so the quick loot menu doesnt open for animals? (something that could be enabled/disabled in the ini like "disableincombat" as an example). That way, the people who use hunterborn would play much better with both mods without accidently looting the animal.

**Comment by Neondaze** [comment]
I second this request. The previous iteration did not open when using Hunterborn. As I always use Hunterborn I am not sure if it was true compatibility or if searching animals was just removed.

**Comment by SniffleMan** [comment]
Added in 1.7.14

**Comment by thebowchild** [comment]
I ran into some wolves and sabrecats that still displayed the quick loot menu, but mostly it works. TY a lot! You are doing an amazing job!

**Comment by SniffleMan** [comment]
Can you post their formID's?

**Comment by thebowchild** [comment]
I am off the pc right now, but I will get it tomorrow

**Comment by thebowchild** [comment]
Sorry it took me so long to reply, and I am not really sure what is going on with the animals, it seems to be really random, and it would take me way too long to test one by one to get the formIDs. What I noticed is that is happens more in some areas than others, like wolves and sabrecats on eastmarch and bears on the cave near ivarstead. I also use skytest, maybe its something related to it?

**Comment by SniffleMan** [comment]
Should be fixed in 1.9.0

**Comment by thebowchild** [comment]
Seems like its working 100% now. TY and good job!
