### ISSUE TITLE
Key Suggestion

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#27]
The "Run/Walk Modifier" key ("Shift" by default on keyboard) would be a useful one to have, as it's relatively un-used by most people. Would make for a really nice "singleLootModifier" for me personally.

**Comment by SniffleMan** [comment]
Added in 1.11.0

**Comment by Velgus** [comment]
I noticed you implemented it in 1.11.0, but just a heads up, you may not want to call it "toggleRun", as that is technically "Caps Lock" on keyboard default. "Caps Lock" toggles running/walking, "Shift" modifies it when held.

**Comment by SniffleMan** [comment]
That's sprint

**Comment by Velgus** [comment]
Is it? I haven't actually tested the key rebinds yet. That said, you may want to rename that one then, as I assumed the binding for "Sprint" was "Alt".

**Comment by SniffleMan** [comment]
sprint, run, and toggle run are all different keys

**Comment by Velgus** [comment]
I think the things that are confusing me with the naming are:

- I associate sprinting in Skyrim with "Alt" on the keyboard.
- The "Shift" key is actually a modifier - not just a static movement change. If you are currently running from the toggle ("Caps Lock"), then it makes you walk. If you are currently walking from the toggle, it makes you run.

**Comment by SniffleMan** [comment]
This is how the game tracks it internally

**Comment by Velgus** [comment]
Weird. Well alright - just a thought, as I would have had to go in and out of the game multiple times to figure all that out based off the current names. Thank you for the implementation!
