### ISSUE TITLE
The list is not updated

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#29]
(BUG1) If you open the container in the usual way and take the last item, then the list of quickloot remains the same as before the opening of the container. The same applies to pickpocket. (Take the item with the key "Use" not "Take All")
(BUG2) (If container animation is enabled). The container does not close if you take the last item from it using quickloot. He will remain open. (Take the item with the key "Use" not "Take All")
(BUG3) The list of sorting by name begins with the last letter of the alphabet.

**Comment by SniffleMan** [comment]
Should all be fixed in 1.11.1
