### ISSUE TITLE
1.30 first testing 

### ISSUE THREAD

**Issue by fullex2064** [SniffleMan/QuickLootRE#3]
![screenshot1](https://user-images.githubusercontent.com/44735517/47957684-b335e480-df88-11e8-9102-5c1d0b82bbf4.png)

With the latest update release, the widgets for looting have bugged and now all loot looks like it does in the attached screenshot. It makes everything look enchanted and stolen, but once looted the normal widgets display in my inventory. I loaded a save with some already killed enemies and a few live ones, and it seems that both types had suffered from this when the interface would pop up. I have a heavily modded game, but the release i was testing with prior to the latest one was displaying the widgets normally when quicklooting. 

Also, when hovering over a downed opponent and the quickloot menu pops up, if I press the escape key to go into the system menu, the scroll wheel is disabled, and sometimes the system menu freezes and you have to hit escape a few times to exit. Not game breaking or anything, just something I noticed and thought I'd point out in case it might be helpful. 

The last nexus version of quickloot also had a feature for being able to take all loot when pressing the F key, not sure how hard that would be to implement but it comes in handy every now and then. 

Thank you for cracking the code on this one! Hopefully I can be of some help in testing for you!

**Comment by SniffleMan** [comment]
Should all be fixed 1.5.0
