### ISSUE TITLE
Taking items while dialog windows are open

### ISSUE THREAD

**Issue by King-Troller** [SniffleMan/QuickLootRE#30]
This may just be a gamepad issue. Confirming a selection in text boxes also causes the first item in a container to be looted if it's being looked at even though the quickloot menu isn't open. This is particularly a problem when using better vampires to feed on recently killed enemies because it always takes the first item out of their inventory when I try to feed.

**Comment by SniffleMan** [comment]
Let me know if 1.11.1 fixes this

**Comment by King-Troller** [comment]
Just tested 1.11.1. It's fixed.
