### ISSUE TITLE
I don't know this is a bug or a feature

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#31]
If the NPC or Draugr died with a weapon or shield in their hands, then these items will not be visible in the quickloot, but these items can be taken from the floor individually or through the corpse inventory.
Perhaps Bethesda did it for convenience. However, a "Quickloot 1.1f"  for Olddrim sees these items.

**Comment by SVG1** [comment]
Yes i don't have a ussp.
I once had it installed, but some mods worked with him incorrectly and I demolished it.

**Comment by Velgus** [comment]
USSEP should be near the beginning of your load order, and you should let almost every other mod overwrite it. It will not cause issues with other mods in 99.9% of cases (and the for few cases where it does, those mods are poorly made).

That aside - this issue should be closed, it is not a bug related to this mod.

**Comment by SniffleMan** [comment]
Added in 1.11.2.2
