### ISSUE TITLE
Werewolf "Feed" Text Still Doesn't Show w/ Text Hook

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#33]
Just forwarding this one from the Nexus bugs section, and updating to mention this still doesn't work as of 1.11.0. 

You can probably close the bug on Nexus since, since this is slightly different than the original report (which claimed Moonlight Tales was incompatible, which it isn't, it's just a minor UI issue).

The loot menu shows up as normal, and functions, but the "R" key says "Search", while functioning (at least for the 'first' NPC activation) as "Feed".

**Comment by SniffleMan** [comment]
See if 1.12.6 fixes it

**Comment by Velgus** [comment]
So I now crash whenever I target a dead NPC as a werewolf with 1.26.6.

Unfortunately the .NET Script Framework does not seem to be outputting a crash log for this crash. I ensured it's being loaded via "binkw64.log" and "NetScriptFramework.log.txt", and that "Debug.CrashLog.Enabled = 1" in "NetScriptFramework.config.txt", but no crash log appears from this crash.

**Comment by SniffleMan** [comment]
Does SKSE make a crashlog?

**Comment by Velgus** [comment]
Just a correction - the crash is anytime the QuickLoot menu is opened (it seems some others are having the same issue on the Nexus thread - including the lack of Script Framework crash log output).

I just enabled MiniDumps and tested - SKSE also does not output a log for this (it created the "Crashdumps" folder, but it didn't actually put anything in it).

**Comment by SniffleMan** [comment]
Should be fixed in 1.12.7

**Comment by Velgus** [comment]
Yup - 1.12.7 fixed it, and the Werewolf text hook now works. Before feeding, R shows "Feed", after, it shows "Search". Thanks!
