### ISSUE TITLE
v1.11.2.1 bug

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#35]
Some NPCs in pickpocket mode are not on the list of equipped weapons.

**Comment by SVG1** [comment]
Amendment: Equipped weapons are not visible through the quickloot, even in corpses.

I also wanted to add: can occur CTD before emersion "quickloot" menu, even if the container is empty.
Happens on all versions.

**Comment by SniffleMan** [comment]
Can you add

[Debug]
WriteMinidumps=1

To your skse.ini and upload the crashdump in `Documents\My Games\Skyrim Special Edition\SKSE\Crashdumps` for me?

**Comment by Velgus** [comment]
Yeah, I can confirm the pickpocket issue for equipped weapons with the Misdirection perk - you can't pickpocket them from 'some' NPCs.

Images: 
- [Fralia QuickLoot](https://i.imgur.com/ejd1Ao2.jpg) vs. [Fralia Vanilla](https://i.imgur.com/wW8XKqn.png)
- [Idolaf QuickLoot](https://i.imgur.com/LwiO313.jpg) vs. [Idolaf Vanilla](https://i.imgur.com/epro31T.png)

I also noticed a behavior I never knew before, but Misdirection doesn't work if the person you're trying to take the weapon from has line-of-sight of you, even in the vanilla interface (though you can still try to pickpocket other things). This doesn't seem to be directly related to this issue though.

**Comment by SVG1** [comment]
[https://drive.google.com/open?id=1s3aN-FRRtOffEGwZpJ3MrFFmhmwJnwQi](url)
Link to dump file

**Comment by SniffleMan** [comment]
Let me know if 1.11.2.4 fixes the crash

**Comment by SVG1** [comment]
Played over 4 hours - no crash. Thank you very much! It used to be СTD for 1 hour.
But what is this "-1%" in the place where there should be a chance of pickpocketing? Appears in any container other than pickpocketing.

**Comment by SniffleMan** [comment]
I was working on a fix for displaying zero pickpocket chance and forgot to include the new swf

**Comment by SVG1** [comment]
It's clear. 
How about the fact that an equipped weapon does not display “quickloot” in corpses and in pickpocketing?

PS: The bug with the visibility of dropped items in the "quickloot"  - really fixed !

**Comment by SVG1** [comment]
Still found that the books are also not visible in the inventory NPCs.
In general, all the problems relate only to the inventory of NPCs. With other containers - no problem.

**Comment by SniffleMan** [comment]
Equipped weapons now display
Books not showing is really weird tho

**Comment by SVG1** [comment]
SniffleMan, you are not from Russia? Just the time the file was created coincides with my time zone.

**Comment by SniffleMan** [comment]
Nope, I just have a bad sleep schedule

**Comment by SniffleMan** [comment]
See if 1.11.6 fixes it

**Comment by SVG1** [comment]
Everything also, no change

**Comment by SniffleMan** [comment]
Should be fixed in 1.11.7

**Comment by SVG1** [comment]
Yes, it works fine now. I will keep you updated.
