### ISSUE TITLE
Menu not updating when inventory changes

### ISSUE THREAD

**Issue by King-Troller** [SniffleMan/QuickLootRE#4]
The items listed in the quickloot window only update when first shown instead of anytime the inventory of the object changes. I only notice this because I'm using [AutoHarvest](https://www.nexusmods.com/skyrimspecialedition/mods/17622). I'm fairly sure it's not a conflict between mods since it showed the items being removed in older versions of QuickLoot.

**Comment by SniffleMan** [comment]
Which version did it work on?

**Comment by King-Troller** [comment]
I guess saying older is kinda misleading. It was working that way with the most recent version on Nexus. As far as I can remember it worked on every version released for SSE.

**Comment by SniffleMan** [comment]
Should be fixed in 1.4.1

**Comment by King-Troller** [comment]
Works great now. Nice work.

**Comment by King-Troller** [comment]
Every version 1.7+ seems to be having this issue again
