### ISSUE TITLE
1.12.1 (22 november) bug

### ISSUE THREAD

**Issue by SilentPrayeCG** [SniffleMan/QuickLootRE#40]
updated, (version before was ok), and something strange, overlay appear, but i can't interact with it.
every buttons are marked as "esc", and mouse wheel zooming camera instead scrolling through items.

![screenshot53](https://user-images.githubusercontent.com/17825684/48920039-560ebe00-eeb8-11e8-9651-4abbdb3aa171.png)

**Comment by SilentPrayeCG** [comment]
i didn't installed hookshare though, but i didn't use that unpause menus mod

**Comment by SniffleMan** [comment]
You have to install hookshare

**Comment by SilentPrayeCG** [comment]
Thanks, now it works ok.
Sorry for bothering you, I've misunderstood requirements, thought it's only if i use both mods.
