### ISSUE TITLE
Huge mess with latest build

### ISSUE THREAD

**Issue by thebowchild** [SniffleMan/QuickLootRE#41]
Using 1.12.7 made a mess to me. Trying to roll down thru the cointainer's loot simply zoom in and out of character (along with getting up/down on the item list). Pressing all buttons also doesnt work anymore (the take option makes the cointainer open like vanilla, the take all sheaths weapon and there is a third option that I am not even sure what it does).

**Comment by SniffleMan** [comment]
Have you installed hookshare?

**Comment by thebowchild** [comment]
My bad, I have been away these past days and didnt even know about hookshare. It seems it fixed it ^^ TY
