### ISSUE TITLE
Crashes on Non-NPC Containers

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/QuickLootRE#43]
So, while issue #33 was fixed with 1.12.7, it seems normal containers cause crashes now. The container QuickLoot interface doesn't open, the moment the container is targeted, the game CTDs.

NPC looting appears to work fine.

.NET Script Framework Log:
[Crash_2018_11_29_17-21-13.txt](https://github.com/SniffleMan/QuickLootRE/files/2631596/Crash_2018_11_29_17-21-13.txt)

**Comment by SniffleMan** [comment]
See if 1.12.8 helps

**Comment by Velgus** [comment]
Problem still exists in 1.12.8 - no change (NPCs still work, containers don't).

New .NET Script Framework Log:
[Crash_2018_11_29_20-57-9.txt](https://github.com/SniffleMan/QuickLootRE/files/2632088/Crash_2018_11_29_20-57-9.txt)

**Comment by SniffleMan** [comment]
Does it crash without engine fixes?

**Comment by Velgus** [comment]
Yes.

Crash Log wo/ Engine Fixes:
[Crash_2018_11_29_21-2-27.txt](https://github.com/SniffleMan/QuickLootRE/files/2632097/Crash_2018_11_29_21-2-27.txt)

**Comment by SniffleMan** [comment]
Do you have a specific container this happens on?

**Comment by Velgus** [comment]
I'm using the pot over the fire in Embershard Mine (the area the two bandits are talking when you enter). 

That said, while testing earlier (with 1.12.7), I had also experienced the crash on the 'other' pot there, and a random container in Dragonsreach. It doesn't occur on 'empty' containers or NPCs, has ocurred on all 3 containers with items I've tried.

**Comment by SniffleMan** [comment]
What settings are you using?

**Comment by Velgus** [comment]
On QuickLoot? Default - no changes from what comes with the latest update.

{
	"disableInCombat": true,
	"disableTheft": false,
	"disablePickpocketing": false,
	"disableIfEmpty": true,
	"disableSingleLoot": false,
	"disableForAnimals": false,
	"disableActiTextHook": false,
	"disableAnimations": false,
	"itemLimit": 100,
	"scale": -1.0,
	"positionX": -1.0,
	"positionY": -1.0,
	"opacity": -1.0,
	"singleLootModifier": "sprint",
	"takeMethod": "activate",
	"takeAllMethod": "togglePOV",
	"searchMethod": "readyWeapon",
	"interfaceStyle": "dialogue",
	"sortOrder": [
		"stolen",
		"type",
		"name",
		"value",
		"count"
	]
}

**Comment by SniffleMan** [comment]
Does it happen on vanilla?

**Comment by Velgus** [comment]
Tried with only SKSE, QuickLoot (and HookShare), and .NET Script Framework. It actually becomes even worse, crashing on NPCs as well.

Vanilla Crash Log on NPC:
[Crash_2018_11_29_21-43-14.txt](https://github.com/SniffleMan/QuickLootRE/files/2632180/Crash_2018_11_29_21-43-14.txt)

Vanilla Crash Log on Container:
[Crash_2018_11_29_21-44-58.txt](https://github.com/SniffleMan/QuickLootRE/files/2632181/Crash_2018_11_29_21-44-58.txt)

**Comment by SniffleMan** [comment]
Can you provide an skse minidump?

**Comment by Velgus** [comment]
I actually had forgotten SkyUI was a requirement - with SkyUI enabled as well (and otherwise vanilla), it doesn't crash for either NPCs or containers.

**Comment by Velgus** [comment]
Here's the dump from my modded game:
[2018-11-30_05.57.50.zip](https://github.com/SniffleMan/QuickLootRE/files/2632221/2018-11-30_05.57.50.zip)

**Comment by SniffleMan** [comment]
See if 1.12.9 fixes it

**Comment by Velgus** [comment]
Nope, still the same issue on my modded setup (NPCs are fine, containers are not).

New Crash Log and Minidump:
[Crash_2018_11_30_10-14-51.txt](https://github.com/SniffleMan/QuickLootRE/files/2634528/Crash_2018_11_30_10-14-51.txt)
[2018-11-30_18.13.28.zip](https://github.com/SniffleMan/QuickLootRE/files/2634529/2018-11-30_18.13.28.zip)

**Comment by SniffleMan** [comment]
Can you try 1.12.9.1 and provide the log if it crashes?

**Comment by Velgus** [comment]
Yup, still crashes, here are the logs.
[Crash_2018_11_30_11-2-48.txt](https://github.com/SniffleMan/QuickLootRE/files/2634663/Crash_2018_11_30_11-2-48.txt)
[2018-11-30_19.01.41.zip](https://github.com/SniffleMan/QuickLootRE/files/2634664/2018-11-30_19.01.41.zip)

**Comment by SniffleMan** [comment]
Can you post the quickloot log?

**Comment by Velgus** [comment]
Sure. Sorry for the delay.
[QuickLootRE.log](https://github.com/SniffleMan/QuickLootRE/files/2635044/QuickLootRE.log)

This is after another reproduction of the crash that I did quick (not the ones from earlier).

**Comment by SniffleMan** [comment]
See if 1.12.9.2 helps

**Comment by Velgus** [comment]
That seems to have fixed the crashing - the usual case (the pot) worked fine, as did the NPCs. I also ran around to a few other containers and teleported to Dragonsreach and did the same there - no crashes.

**Comment by SniffleMan** [comment]
Can you post the quickloot log one more time?

**Comment by Velgus** [comment]
Yup.
[QuickLootRE.log](https://github.com/SniffleMan/QuickLootRE/files/2635109/QuickLootRE.log)

**Comment by SniffleMan** [comment]
Fix pushed in 1.12.10
