### ISSUE TITLE
SniffleMan, Please help to compile

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#44]
I wanted to compile the source, but due to errors I can't. 
Here list of errors:

1>------ Build started: Project: QuickLootRE, Configuration: Release x64 ------
1>Delegates.cpp
1>HaACTITextOverrideVisitor.cpp
1>ActiveEffect.cpp
1>Actor.cpp
1>ActorProcessManager.cpp
1>ActorState.cpp
1>Hooks.cpp
1>InventoryList.cpp
1>ItemData.cpp
1>Forms.cpp
1>LootMenu.cpp
1>main.cpp
1>Events.cpp
1>ActorValueOwner.cpp
1>BaseExtraList.cpp
1>BGSBipedObjectForm.cpp
1>BGSEntryPointPerkEntry.cpp
1>BSInputDevice.cpp
1>BSTArray.cpp
1>BSWin32KeyboardDevice.cpp
1>Compiling...
1>ButtonEvent.cpp
1>EffectSetting.cpp
1>EventDispatcherList.cpp
1>ExtraContainerChanges.cpp
1>GFxLoader.cpp
1>GFxState.cpp
1>IMenu.cpp
1>InputEventDispatcher.cpp
1>InputManager.cpp
1>InventoryChanges.cpp
1>InventoryEntryData.cpp
1>MagicItem.cpp
1>MagicTarget.cpp
1>MenuControls.cpp
1>MenuEventHandler.cpp
1>MenuManager.cpp
1>NiAVObject.cpp
1>NiControllerManager.cpp
1>NiControllerSequence.cpp
1>NiNode.cpp
1>Compiling...
1>NiObjectNET.cpp
1>PlayerCharacter.cpp
1>PlayerControls.cpp
1>PlayerInputHandler.cpp
1>TESActorBaseData.cpp
1>TESFaction.cpp
1>TESLeveledList.cpp
1>TESLevItem.cpp
1>TESNPC.cpp
1>TESObjectBOOK.cpp
1>TESObjectLIGH.cpp
1>TESObjectREFR.cpp
1>UIManager.cpp
1>Settings.cpp
1>Utility.cpp
1>   Creating library E:\9\1\2\QuickLootRE-1.11.7\x64\Release\QuickLootRE.lib and object E:\9\1\2\QuickLootRE-1.11.7\x64\Release\QuickLootRE.exp
1>Delegates.obj : error LNK2001: unresolved external symbol "class RelocPtr<class PlayerCharacter *> g_thePlayer" (?g_thePlayer@@3V?$RelocPtr@PEAVPlayerCharacter@@@@A)
1>Delegates.obj : error LNK2001: unresolved external symbol "void * __cdecl ScaleformHeap_Allocate(unsigned long)" (?ScaleformHeap_Allocate@@YAPEAXK@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "class RelocPtr<class SettingCollectionMap *> g_gameSettingCollection" (?g_gameSettingCollection@@3V?$RelocPtr@PEAVSettingCollectionMap@@@@A)
1>Delegates.obj : error LNK2001: unresolved external symbol "void __cdecl ScaleformHeap_Free(void *)" (?ScaleformHeap_Free@@YAXPEAX@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: bool __cdecl GFxValue::PushBack(class GFxValue *)" (?PushBack@GFxValue@@QEAA_NPEAV1@@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: bool __cdecl GFxValue::SetMember(char const *,class GFxValue *)" (?SetMember@GFxValue@@QEAA_NPEBDPEAV1@@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: void __cdecl GFxValue::SetString(char const *)" (?SetString@GFxValue@@QEAAXPEBD@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: void __cdecl GFxValue::SetNumber(double)" (?SetNumber@GFxValue@@QEAAXN@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: void __cdecl GFxValue::SetBool(bool)" (?SetBool@GFxValue@@QEAAX_N@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: __cdecl GFxValue::~GFxValue(void)" (??1GFxValue@@QEAA@XZ)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: class Setting * __cdecl SettingCollectionMap::Get(char const *)" (?Get@SettingCollectionMap@@QEAAPEAVSetting@@PEBD@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "void __cdecl Heap_Free(void *)" (?Heap_Free@@YAXPEAX@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "void * __cdecl Heap_Allocate(unsigned __int64)" (?Heap_Allocate@@YAPEAX_K@Z)
1>Delegates.obj : error LNK2001: unresolved external symbol "public: static void __cdecl IDebugLog::Log(enum IDebugLog::LogLevel,char const *,char *)" (?Log@IDebugLog@@SAXW4LogLevel@1@PEBDPEAD@Z)
1>ActiveEffect.obj : error LNK2001: unresolved external symbol "public: static unsigned __int64 RelocationManager::s_baseAddr" (?s_baseAddr@RelocationManager@@2_KA)
1>Actor.obj : error LNK2001: unresolved external symbol "public: void __cdecl Actor::UpdateHairColor(void)" (?UpdateHairColor@Actor@@QEAAXXZ)
1>Actor.obj : error LNK2001: unresolved external symbol "public: void __cdecl Actor::UpdateSkinColor(void)" (?UpdateSkinColor@Actor@@QEAAXXZ)
1>Actor.obj : error LNK2001: unresolved external symbol "public: class TESForm * __cdecl Actor::GetEquippedObject(bool)" (?GetEquippedObject@Actor@@QEAAPEAVTESForm@@_N@Z)
1>ActorProcessManager.obj : error LNK2001: unresolved external symbol "public: void __cdecl ActorProcessManager::UpdateEquipment_Hooked(class Actor *)" (?UpdateEquipment_Hooked@ActorProcessManager@@QEAAXPEAVActor@@@Z)
1>Hooks.obj : error LNK2001: unresolved external symbol "public: char const * __cdecl BSString::Get(void)" (?Get@BSString@@QEAAPEBDXZ)
1>Hooks.obj : error LNK2001: unresolved external symbol "void __cdecl SafeWrite64(unsigned __int64,unsigned __int64)" (?SafeWrite64@@YAX_K0@Z)
1>Hooks.obj : error LNK2001: unresolved external symbol "public: __cdecl StringCache::Ref::Ref(char const *)" (??0Ref@StringCache@@QEAA@PEBD@Z)
1>InventoryList.obj : error LNK2001: unresolved external symbol "class RelocPtr<unsigned long> g_invalidRefHandle" (?g_invalidRefHandle@@3V?$RelocPtr@K@@A)
1>InventoryList.obj : error LNK2001: unresolved external symbol "void const * const RTTI_TESForm" (?RTTI_TESForm@@3PEBXEB)
1>InventoryList.obj : error LNK2001: unresolved external symbol "public: void __cdecl NiRefObject::DecRef(void)" (?DecRef@NiRefObject@@QEAAXXZ)
1>InventoryList.obj : error LNK2001: unresolved external symbol "public: void __cdecl NiRefObject::IncRef(void)" (?IncRef@NiRefObject@@QEAAXXZ)
1>InventoryList.obj : error LNK2001: unresolved external symbol "void const * const RTTI_TESFullName" (?RTTI_TESFullName@@3PEBXEB)
1>InventoryList.obj : error LNK2001: unresolved external symbol "void * __cdecl Runtime_DynamicCast(void *,void const *,void const *)" (?Runtime_DynamicCast@@YAPEAXPEAXPEBX1@Z)
1>ItemData.obj : error LNK2001: unresolved external symbol "class RelocAddr<class TESForm * (__cdecl*)(unsigned long)> LookupFormByID" (?LookupFormByID@@3V?$RelocAddr@P6APEAVTESForm@@K@Z@@A)
1>ItemData.obj : error LNK2001: unresolved external symbol "void const * const RTTI_TESWeightForm" (?RTTI_TESWeightForm@@3PEBXEB)
1>ItemData.obj : error LNK2001: unresolved external symbol "void const * const RTTI_TESEnchantableForm" (?RTTI_TESEnchantableForm@@3PEBXEB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "class NiRTTI const * const NiRTTI_NiControllerManager" (?NiRTTI_NiControllerManager@@3PEBVNiRTTI@@EB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "void const * const RTTI_BSKeyboardDevice" (?RTTI_BSKeyboardDevice@@3PEBXEB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "void const * const RTTI_BSGamepadDevice" (?RTTI_BSGamepadDevice@@3PEBXEB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "void const * const RTTI_BSWin32KeyboardDevice" (?RTTI_BSWin32KeyboardDevice@@3PEBXEB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "void const * const RTTI_BSWin32GamepadDevice" (?RTTI_BSWin32GamepadDevice@@3PEBXEB)
1>LootMenu.obj : error LNK2001: unresolved external symbol "class NiObject * __cdecl DoNiRTTICast(class NiObject *,class NiRTTI const *)" (?DoNiRTTICast@@YAPEAVNiObject@@PEAV1@PEBVNiRTTI@@@Z)
1>main.obj : error LNK2001: unresolved external symbol "private: static enum IDebugLog::LogLevel IDebugLog::printLevel" (?printLevel@IDebugLog@@0W4LogLevel@1@A)
1>main.obj : error LNK2001: unresolved external symbol "private: static enum IDebugLog::LogLevel IDebugLog::logLevel" (?logLevel@IDebugLog@@0W4LogLevel@1@A)
1>main.obj : error LNK2001: unresolved external symbol "public: static class InputEventDispatcher * __cdecl InputEventDispatcher::GetSingleton(void)" (?GetSingleton@InputEventDispatcher@@SAPEAV1@XZ)
1>main.obj : error LNK2001: unresolved external symbol "public: static void __cdecl IDebugLog::OpenRelative(int,char const *)" (?OpenRelative@IDebugLog@@SAXHPEBD@Z)
1>BaseExtraList.obj : error LNK2001: unresolved external symbol "public: class BSExtraData * __cdecl BaseExtraList::GetByType(unsigned long)" (?GetByType@BaseExtraList@@QEAAPEAVBSExtraData@@K@Z)
1>BaseExtraList.obj : error LNK2001: unresolved external symbol "public: char const * __cdecl BaseExtraList::GetDisplayName(class TESForm *)" (?GetDisplayName@BaseExtraList@@QEAAPEBDPEAVTESForm@@@Z)
1>BaseExtraList.obj : error LNK2001: unresolved external symbol "public: bool __cdecl BaseExtraList::CheckContainerExtraData(bool)" (?CheckContainerExtraData@BaseExtraList@@QEAA_N_N@Z)
1>BaseExtraList.obj : error LNK2001: unresolved external symbol "public: bool __cdecl BaseExtraList::Add(unsigned char,class BSExtraData *)" (?Add@BaseExtraList@@QEAA_NEPEAVBSExtraData@@@Z)
1>BaseExtraList.obj : error LNK2001: unresolved external symbol "public: bool __cdecl BaseExtraList::Remove(unsigned char,class BSExtraData *)" (?Remove@BaseExtraList@@QEAA_NEPEAVBSExtraData@@@Z)
1>EventDispatcherList.obj : error LNK2001: unresolved external symbol "class RelocAddr<class EventDispatcherList * (__cdecl*)(void)> GetEventDispatcherList" (?GetEventDispatcherList@@3V?$RelocAddr@P6APEAVEventDispatcherList@@XZ@@A)
1>ExtraContainerChanges.obj : error LNK2001: unresolved external symbol "public: struct ExtraContainerChanges::FoundHotkeyData __cdecl ExtraContainerChanges::FindHotkey(long)const " (?FindHotkey@ExtraContainerChanges@@QEBA?AUFoundHotkeyData@1@J@Z)
1>ExtraContainerChanges.obj : error LNK2001: unresolved external symbol "public: struct ExtraContainerChanges::FoundHotkeyData __cdecl ExtraContainerChanges::FindHotkey(class TESForm *)const " (?FindHotkey@ExtraContainerChanges@@QEBA?AUFoundHotkeyData@1@PEAVTESForm@@@Z)
1>ExtraContainerChanges.obj : error LNK2001: unresolved external symbol "public: struct ExtraContainerChanges::FoundEquipData __cdecl ExtraContainerChanges::FindEquipped(class FormMatcher &,bool,bool)const " (?FindEquipped@ExtraContainerChanges@@QEBA?AUFoundEquipData@1@AEAVFormMatcher@@_N1@Z)
1>GFxLoader.obj : error LNK2001: unresolved external symbol "public: static class GFxLoader * __cdecl GFxLoader::GetSingleton(void)" (?GetSingleton@GFxLoader@@SAPEAV1@XZ)
1>InputManager.obj : error LNK2001: unresolved external symbol "public: unsigned char __cdecl InputManager::AllowTextInput(bool)" (?AllowTextInput@InputManager@@QEAAE_N@Z)
1>InputManager.obj : error LNK2001: unresolved external symbol "public: static class InputManager * __cdecl InputManager::GetSingleton(void)" (?GetSingleton@InputManager@@SAPEAV1@XZ)
1>InputManager.obj : error LNK2001: unresolved external symbol "public: __cdecl StringCache::Ref::Ref(void)" (??0Ref@StringCache@@QEAA@XZ)
1>InventoryChanges.obj : error LNK2001: unresolved external symbol "public: void __cdecl ExtraContainerChanges::Data::GetEquipItemData(struct InventoryEntryData::EquipData &,class TESForm *,long)const " (?GetEquipItemData@Data@ExtraContainerChanges@@QEBAXAEAUEquipData@InventoryEntryData@@PEAVTESForm@@J@Z)
1>InventoryChanges.obj : error LNK2001: unresolved external symbol "public: class InventoryEntryData * __cdecl ExtraContainerChanges::Data::CreateEquipEntryData(class TESForm *)" (?CreateEquipEntryData@Data@ExtraContainerChanges@@QEAAPEAVInventoryEntryData@@PEAVTESForm@@@Z)
1>InventoryChanges.obj : error LNK2001: unresolved external symbol "public: class InventoryEntryData * __cdecl ExtraContainerChanges::Data::FindItemEntry(class TESForm *)const " (?FindItemEntry@Data@ExtraContainerChanges@@QEBAPEAVInventoryEntryData@@PEAVTESForm@@@Z)
1>InventoryEntryData.obj : error LNK2001: unresolved external symbol "public: void __cdecl InventoryEntryData::GetEquipItemData(struct InventoryEntryData::EquipData &,long,long)const " (?GetEquipItemData@InventoryEntryData@@QEBAXAEAUEquipData@1@JJ@Z)
1>InventoryEntryData.obj : error LNK2001: unresolved external symbol "public: void __cdecl InventoryEntryData::GetExtraWornBaseLists(class BaseExtraList * *,class BaseExtraList * *)const " (?GetExtraWornBaseLists@InventoryEntryData@@QEBAXPEAPEAVBaseExtraList@@0@Z)
1>MenuControls.obj : error LNK2001: unresolved external symbol "public: static class MenuControls * __cdecl MenuControls::GetSingleton(void)" (?GetSingleton@MenuControls@@SAPEAV1@XZ)
1>MenuManager.obj : error LNK2001: unresolved external symbol "public: class GFxMovieView * __cdecl MenuManager::GetMovieView(struct StringCache::Ref *)" (?GetMovieView@MenuManager@@QEAAPEAVGFxMovieView@@PEAURef@StringCache@@@Z)
1>MenuManager.obj : error LNK2001: unresolved external symbol "public: class IMenu * __cdecl MenuManager::GetMenu(struct StringCache::Ref *)" (?GetMenu@MenuManager@@QEAAPEAVIMenu@@PEAURef@StringCache@@@Z)
1>MenuManager.obj : error LNK2001: unresolved external symbol "public: bool __cdecl MenuManager::IsMenuOpen(struct StringCache::Ref *)" (?IsMenuOpen@MenuManager@@QEAA_NPEAURef@StringCache@@@Z)
1>NiNode.obj : error LNK2001: unresolved external symbol "public: static class NiNode * __cdecl NiNode::Create(unsigned long)" (?Create@NiNode@@SAPEAV1@K@Z)
1>NiObjectNET.obj : error LNK2001: unresolved external symbol "public: class NiExtraData * __cdecl NiObjectNET::GetExtraData(struct StringCache::Ref)" (?GetExtraData@NiObjectNET@@QEAAPEAVNiExtraData@@URef@StringCache@@@Z)
1>NiObjectNET.obj : error LNK2001: unresolved external symbol "public: long __cdecl NiObjectNET::GetIndexOf(class NiExtraData *)" (?GetIndexOf@NiObjectNET@@QEAAJPEAVNiExtraData@@@Z)
1>NiObjectNET.obj : error LNK2001: unresolved external symbol "public: bool __cdecl NiObjectNET::RemoveExtraData(class NiExtraData *)" (?RemoveExtraData@NiObjectNET@@QEAA_NPEAVNiExtraData@@@Z)
1>NiObjectNET.obj : error LNK2001: unresolved external symbol "public: void __cdecl NiObjectNET::AddExtraData(class NiExtraData *)" (?AddExtraData@NiObjectNET@@QEAAXPEAVNiExtraData@@@Z)
1>PlayerCharacter.obj : error LNK2001: unresolved external symbol "public: class TintMask * __cdecl PlayerCharacter::GetOverlayTintMask(class TintMask *)" (?GetOverlayTintMask@PlayerCharacter@@QEAAPEAVTintMask@@PEAV2@@Z)
1>PlayerControls.obj : error LNK2001: unresolved external symbol "public: class PlayerControls * __cdecl PlayerControls::ctor_Hook(void)" (?ctor_Hook@PlayerControls@@QEAAPEAV1@XZ)
1>PlayerControls.obj : error LNK2001: unresolved external symbol "public: static class PlayerControls * __cdecl PlayerControls::GetSingleton(void)" (?GetSingleton@PlayerControls@@SAPEAV1@XZ)
1>TESNPC.obj : error LNK2001: unresolved external symbol "public: class TESNPC * __cdecl TESNPC::GetRootTemplate(void)" (?GetRootTemplate@TESNPC@@QEAAPEAV1@XZ)
1>TESNPC.obj : error LNK2001: unresolved external symbol "public: class BGSHeadPart * __cdecl TESNPC::GetCurrentHeadPartByType(unsigned long)" (?GetCurrentHeadPartByType@TESNPC@@QEAAPEAVBGSHeadPart@@K@Z)
1>TESNPC.obj : error LNK2001: unresolved external symbol "public: class BGSHeadPart * __cdecl TESNPC::GetHeadPartOverlayByType(unsigned long)" (?GetHeadPartOverlayByType@TESNPC@@QEAAPEAVBGSHeadPart@@K@Z)
1>TESNPC.obj : error LNK2001: unresolved external symbol "public: void __cdecl TESNPC::SetHairColor(class BGSColorForm *)" (?SetHairColor@TESNPC@@QEAAXPEAVBGSColorForm@@@Z)
1>TESNPC.obj : error LNK2001: unresolved external symbol "public: void __cdecl TESNPC::SetFaceTexture(class BGSTextureSet *)" (?SetFaceTexture@TESNPC@@QEAAXPEAVBGSTextureSet@@@Z)
1>TESObjectBOOK.obj : error LNK2001: unresolved external symbol "public: unsigned long __cdecl TESObjectBOOK::Data::GetSanitizedType(void)" (?GetSanitizedType@Data@TESObjectBOOK@@QEAAKXZ)
1>TESObjectREFR.obj : error LNK2001: unresolved external symbol "class RelocAddr<bool (__cdecl*)(unsigned long *,class TESObjectREFR * *)> LookupREFRByHandle" (?LookupREFRByHandle@@3V?$RelocAddr@P6A_NPEAKPEAPEAVTESObjectREFR@@@Z@@A)
1>TESObjectREFR.obj : error LNK2001: unresolved external symbol "public: static class ExtraTextDisplayData * __cdecl ExtraTextDisplayData::Create(void)" (?Create@ExtraTextDisplayData@@SAPEAV1@XZ)
1>TESObjectREFR.obj : error LNK2001: unresolved external symbol "class RelocAddr<bool (__cdecl*)(unsigned long *,class BSHandleRefObject * *)> LookupREFRObjectByHandle" (?LookupREFRObjectByHandle@@3V?$RelocAddr@P6A_NPEAKPEAPEAVBSHandleRefObject@@@Z@@A)
1>TESObjectREFR.obj : error LNK2001: unresolved external symbol "public: unsigned long __cdecl TESObjectREFR::CreateRefHandle(void)" (?CreateRefHandle@TESObjectREFR@@QEAAKXZ)
1>UIManager.obj : error LNK2001: unresolved external symbol "public: void __cdecl UIManager::QueueCommand(class UIDelegate *)" (?QueueCommand@UIManager@@QEAAXPEAVUIDelegate@@@Z)
1>UIManager.obj : error LNK2001: unresolved external symbol "public: void __cdecl UIManager::QueueCommand(class UIDelegate_v1 *)" (?QueueCommand@UIManager@@QEAAXPEAVUIDelegate_v1@@@Z)
1>UIManager.obj : error LNK2001: unresolved external symbol "public: void __cdecl UIManager::ProcessCommands(void)" (?ProcessCommands@UIManager@@QEAAXXZ)
1>E:\9\1\2\QuickLootRE-1.11.7\x64\Release\QuickLootRE.dll : fatal error LNK1120: 84 unresolved externals
1>Done building project "QuickLootRE.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by SniffleMan** [comment]
Are you compiling SKSE as a static lib?

**Comment by SVG1** [comment]
What is "static lib" ? Sorry, i'm not a programmer. I just drop the folders "common & skse64" near the quickloot folder. Without these folders, the compiler swears at the missing files.

**Comment by SVG1** [comment]
I compiled skse, it turned out 2 libraries "common.lib, skse64_common.lib". How to hook  them with the project?

**Comment by SniffleMan** [comment]
Add the projects to the same solution

**Comment by SVG1** [comment]
All the same. Maybe needed QuickLoot.pdb?

**Comment by SniffleMan** [comment]
the .pdb is for debugging
