### ISSUE TITLE
Game freezes 2-3 seconds and CTD on looting+ suggestions

### ISSUE THREAD

**Issue by thebowchild** [SniffleMan/QuickLootRE#5]
I can view all items inside any container (tested on qasmoke with hundred of items) but when I click to loot any item, my game freezes for like 2-3 seconds and CTD. Happened all the times I've tried with any container. Also three little suggestions (if possible): Add a "loot all" key like the nexus version has, make it possible to quickloot while in combat and (this is a little personal taste) make the loot windons have some transparency (kinda like the nexus version too).

**Comment by King-Troller** [comment]
You can already use it in combat. Just enable it in the json. And the crashes may be cause by another mod interfering. I'm using a heavily modded (~350 mods) setup and haven't had any crashes from it since the 1.0 release

**Comment by thebowchild** [comment]
Do you have any idea what mods could be causing conflict? I dont really know what to look for

**Comment by thebowchild** [comment]
Ok I am back after some testing on the newest version. It seems that the CTD is now very random, happening a couple of times, and the freeze is completly gone. I managed to add loot while in combat and  transparency ( ty for the tip about json). It seems to me the mod doesnt work very well with hunterborn, the skinning dialogue just appears after Ive looted all items of the animal (the nexus version works with it, so maybe there is some insight there?). I also have the same issue and the other guys with all items showing stolen and enchanted, and the search key not always work, sometimes nothing happens and sometimes after a delay it opens the original looting menu twice. And the last suggestions: add a way to loot a single item (the nexus version if you click on item holding shift it loots only one out of the quantity), again a "loot all" key and maybe if possible add the chance (%) of pickpocketing too. Sorry if I am bothering too much, Im just excited that someone is doing this and I wanna help anyway I can.

**Comment by SniffleMan** [comment]
What version are you using?

**Comment by thebowchild** [comment]
The last one you posted, 1.3.0 (the freeze+CTD was on 1.0 but now on 1.3 the freeze is gone, only some ctd from time to time)

**Comment by SniffleMan** [comment]
Single loot is already implemented, check your settings if you've disabled it.
Icon labels are fixed on 1.4.0.
Opening the container is buggy when animations are enabled. Try disabling it in the settings.

**Comment by thebowchild** [comment]
Im not really sure how to download 1.4.0, here I only see the 1.3.0 release

**Comment by thebowchild** [comment]
Back with news! For some reason I was only seeing version 1.3.0, but I found the updates. Ok, so single item pickup is indeed on, labels are now working fine. About hunterborn, it shows animal loot like the other npcs but if I press the ''search" key, then it opens the hunterborn menu, so its not that bad. And the get all items options doesnt work for me, I have the keys rebinded, so that key is the same used to change to first person, and thats what happends instead of looting all.

**Comment by bowdown2q** [comment]
This CTD only seems to happen when looting one using a controller - steam controller.
