### ISSUE TITLE
Loot window not closing when it should

### ISSUE THREAD

**Issue by King-Troller** [SniffleMan/QuickLootRE#7]
The quickloot menu stays open on top of the inventory and magic menus and intercepts input from any keys that are used by it. I'm using SkyUI (obviously from the pic) so idk if that would have an effect on it.

![20181104213058_1](https://user-images.githubusercontent.com/25571946/47975390-9dedb280-e07b-11e8-8021-f2b66a2244b2.jpg)

**Comment by SniffleMan** [comment]
Should be fixed in 1.5.0

**Comment by King-Troller** [comment]
Wow you work fast.
