### ISSUE TITLE
You can make...

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#8]
Can you make it possible to customize the sorting of items through an ini-file?
It would also be nice to make colored icons of items

**Comment by King-Troller** [comment]
Adding to this. If it is somehow possible to use the SkyUI inventory icons that would be awesome.

**Comment by SniffleMan** [comment]
Added sorting in 1.6.0

**Comment by SniffleMan** [comment]
I'm no artist, but the swf is built using the SkUI dev kit. the icons should already be the SkyUI icons.
